backend:
  name: git-gateway
  repo: smikton/thin-slice
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/e398bd95-fa0b-4b93-8886-126bc34b3e82/pkce
  auth_token_endpoint: /sites/e398bd95-fa0b-4b93-8886-126bc34b3e82/token
  gateway_url: https://gateway.decapbridge.com

media_folder: "my-blog/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "my-blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "gapyear"
    label: "Gap Year"
    folder: "my-blog/gap-year-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "gap-year-post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About"
        file: "my-blog/about.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
          - {label: "Title", name: "title", widget: "hidden", default: "About"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/about/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "library"
        label: "Library"
        file: "my-blog/library.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
          - {label: "Title", name: "title", widget: "hidden", default: "Library"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/library/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "projects"
        label: "Projects"
        file: "my-blog/projects.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page.njk"}
          - {label: "Title", name: "title", widget: "hidden", default: "Projects"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/projects/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "gap-year-intro"
        label: "Gap Year Intro"
        file: "my-blog/gap-year.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "gap-year-listing.njk"}
          - {label: "Title", name: "title", widget: "hidden", default: "Gap Year"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/gap-year/"}
          - {label: "Intro Text", name: "body", widget: "markdown"}
